apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: one
servers: 3
image: rancher/k3s:v1.23.6-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - loadbalancer
