apiVersion: k3d.io/v1alpha3
kind: Simple
name: one
servers: 3
agents: 3
image: rancher/k3s:v1.23.6-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --tls-san=my.host.domain
        nodeFilters:
          - server:*
      - arg: --no-deploy=traefik@
        nodeFilters:
          - server:*
