apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-deployment
  namespace: nginx-hello-namespace
spec:
  selector:
    matchLabels:
       app: nginx-hello-app
  replicas: 1
  template:
     metadata:
       labels:
         app: nginx-hello-app
     spec:
       containers:
       - image: nginxdemos/hello:0.3
         name: nginx-hello
         ports:
         - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  namespace: nginx-hello-namespace
spec:
  selector:
    app: nginx-hello-app
  ports:
  - port: 80
    targetPort: 80

---
# htpasswd -c auth user
# password: pass
# cat auth | base64
# rm auth
apiVersion: v1
kind: Secret
metadata:
  name: nginx-hello-basic-auth
  namespace: nginx-hello-namespace
type: Opaque
data:
  auth: dXNlcjokYXByMSR5SFBEM21JSiR0T2xrYkVnRkp3VC50anRyeXVlRzkxCg==

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-ingress
  namespace: nginx-hello-namespace
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: nginx-hello-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - user/pass'
spec:
  rules:
  - host: "example.com.br" # echo "127.0.0.1 example.com.br" | sudo tee -a /etc/hosts
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-hello-service
            port:
              number: 80
